// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include "djinni_support.hpp"
#include "ui_conf_gen.hpp"

namespace djinni_generated {

class NativeUiConfGen final : ::djinni::JniInterface<::gearsbox::UiConfGen, NativeUiConfGen> {
public:
    using CppType = std::shared_ptr<::gearsbox::UiConfGen>;
    using CppOptType = std::shared_ptr<::gearsbox::UiConfGen>;
    using JniType = jobject;

    using Boxed = NativeUiConfGen;

    ~NativeUiConfGen();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeUiConfGen>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeUiConfGen>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeUiConfGen();
    friend ::djinni::JniClass<NativeUiConfGen>;
    friend ::djinni::JniInterface<::gearsbox::UiConfGen, NativeUiConfGen>;

};

}  // namespace djinni_generated
