// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

#include "breakpad_gen.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeBreakpadGen final : ::djinni::JniInterface<::gearsbox::BreakpadGen, NativeBreakpadGen> {
public:
    using CppType = std::shared_ptr<::gearsbox::BreakpadGen>;
    using CppOptType = std::shared_ptr<::gearsbox::BreakpadGen>;
    using JniType = jobject;

    using Boxed = NativeBreakpadGen;

    ~NativeBreakpadGen();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeBreakpadGen>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeBreakpadGen>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeBreakpadGen();
    friend ::djinni::JniClass<NativeBreakpadGen>;
    friend ::djinni::JniInterface<::gearsbox::BreakpadGen, NativeBreakpadGen>;

};

}  // namespace djinni_generated
