// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include "djinni_support.hpp"
#include "text_boarder.hpp"

namespace djinni_generated {

class NativeTextBoarder final : ::djinni::JniEnum {
public:
    using CppType = ::gearsbox::TextBoarder;
    using JniType = jobject;

    using Boxed = NativeTextBoarder;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeTextBoarder>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeTextBoarder>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeTextBoarder() : JniEnum("dyno/fun/gearsbox/TextBoarder") {}
    friend ::djinni::JniClass<NativeTextBoarder>;
};

}  // namespace djinni_generated
