// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include "djinni_support.hpp"
#include "text_align.hpp"

namespace djinni_generated {

class NativeTextAlign final : ::djinni::JniEnum {
public:
    using CppType = ::gearsbox::TextAlign;
    using JniType = jobject;

    using Boxed = NativeTextAlign;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeTextAlign>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeTextAlign>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeTextAlign() : JniEnum("dyno/fun/gearsbox/TextAlign") {}
    friend ::djinni::JniClass<NativeTextAlign>;
};

}  // namespace djinni_generated
