// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include "djinni_support.hpp"
#include "view_conf.hpp"

namespace djinni_generated {

class NativeViewConf final {
public:
    using CppType = ::gearsbox::ViewConf;
    using JniType = jobject;

    using Boxed = NativeViewConf;

    ~NativeViewConf();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeViewConf();
    friend ::djinni::JniClass<NativeViewConf>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("dyno/fun/gearsbox/ViewConf") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ldyno/fun/gearsbox/ViewType;Ldyno/fun/gearsbox/ViewFrame;Ldyno/fun/gearsbox/ArgbColor;ILdyno/fun/gearsbox/TextAlign;Ldyno/fun/gearsbox/TextBoarder;Ljava/lang/String;ZLdyno/fun/gearsbox/TextKeyboard;Ljava/util/ArrayList;Ljava/util/HashMap;)V") };
    const jfieldID field_mId { ::djinni::jniGetFieldID(clazz.get(), "mId", "Ljava/lang/String;") };
    const jfieldID field_mType { ::djinni::jniGetFieldID(clazz.get(), "mType", "Ldyno/fun/gearsbox/ViewType;") };
    const jfieldID field_mFrame { ::djinni::jniGetFieldID(clazz.get(), "mFrame", "Ldyno/fun/gearsbox/ViewFrame;") };
    const jfieldID field_mBgcolor { ::djinni::jniGetFieldID(clazz.get(), "mBgcolor", "Ldyno/fun/gearsbox/ArgbColor;") };
    const jfieldID field_mFontsize { ::djinni::jniGetFieldID(clazz.get(), "mFontsize", "I") };
    const jfieldID field_mTextalign { ::djinni::jniGetFieldID(clazz.get(), "mTextalign", "Ldyno/fun/gearsbox/TextAlign;") };
    const jfieldID field_mTextboarder { ::djinni::jniGetFieldID(clazz.get(), "mTextboarder", "Ldyno/fun/gearsbox/TextBoarder;") };
    const jfieldID field_mText { ::djinni::jniGetFieldID(clazz.get(), "mText", "Ljava/lang/String;") };
    const jfieldID field_mNumericText { ::djinni::jniGetFieldID(clazz.get(), "mNumericText", "Z") };
    const jfieldID field_mKeyboardtype { ::djinni::jniGetFieldID(clazz.get(), "mKeyboardtype", "Ldyno/fun/gearsbox/TextKeyboard;") };
    const jfieldID field_mConstraints { ::djinni::jniGetFieldID(clazz.get(), "mConstraints", "Ljava/util/ArrayList;") };
    const jfieldID field_mSubviews { ::djinni::jniGetFieldID(clazz.get(), "mSubviews", "Ljava/util/HashMap;") };
};

}  // namespace djinni_generated
