// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

#include "djinni_support.hpp"
#include "timer_gen.hpp"

namespace djinni_generated {

class NativeTimerGen final : ::djinni::JniInterface<::gearsbox::TimerGen, NativeTimerGen> {
public:
    using CppType = std::shared_ptr<::gearsbox::TimerGen>;
    using CppOptType = std::shared_ptr<::gearsbox::TimerGen>;
    using JniType = jobject;

    using Boxed = NativeTimerGen;

    ~NativeTimerGen();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeTimerGen>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeTimerGen>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeTimerGen();
    friend ::djinni::JniClass<NativeTimerGen>;
    friend ::djinni::JniInterface<::gearsbox::TimerGen, NativeTimerGen>;

};

}  // namespace djinni_generated
