// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import "GBArgbColor.h"
#include "argb_color.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class GBArgbColor;

namespace djinni_generated {

struct ArgbColor
{
    using CppType = ::gearsbox::ArgbColor;
    using ObjcType = GBArgbColor*;

    using Boxed = ArgbColor;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
