// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import <Foundation/Foundation.h>
@protocol GBCrashHandlerGen;


@protocol GBBreakpadGen

- (void)start;

- (void)stop;

- (void)setUploadUrl;

- (void)setHandler:(nullable id<GBCrashHandlerGen>)hander;

@end
