// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import <Foundation/Foundation.h>


@protocol GBCrashHandlerGen

- (void)header:(nonnull NSString *)path
           url:(nonnull NSString *)url;

@end
