// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import <Foundation/Foundation.h>


@protocol GBPlatformExecutorGen

- (void)endEniting:(BOOL)force;

@end
