// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#include "timer_handler_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol GBTimerHandlerGen;

namespace djinni_generated {

class TimerHandlerGen
{
public:
    using CppType = std::shared_ptr<::gearsbox::TimerHandlerGen>;
    using CppOptType = std::shared_ptr<::gearsbox::TimerHandlerGen>;
    using ObjcType = id<GBTimerHandlerGen>;

    using Boxed = TimerHandlerGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

