// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#include "ui_value_checker_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class GBUiValueCheckerGen;

namespace djinni_generated {

class UiValueCheckerGen
{
public:
    using CppType = std::shared_ptr<::gearsbox::UiValueCheckerGen>;
    using CppOptType = std::shared_ptr<::gearsbox::UiValueCheckerGen>;
    using ObjcType = GBUiValueCheckerGen*;

    using Boxed = UiValueCheckerGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

