// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import "GBViewConf.h"
#import "GBViewConstraint.h"
#import <Foundation/Foundation.h>
@class GBUiConfGen;


@interface GBUiConfGen : NSObject

+ (nullable GBUiConfGen *)instance;

- (BOOL)initialize:(nonnull NSString *)cfg;

- (BOOL)load:(nonnull NSString *)cfg;

- (nonnull NSArray<GBViewConstraint *> *)getConstraints:(nonnull NSString *)name;

- (nonnull GBViewConf *)getViewConf:(nonnull NSString *)nmae;

@end
