// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import "GBUserConfigGen+Private.h"
#import "GBUserConfigGen.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "GBConfigGen+Private.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface GBUserConfigGen ()

- (id)initWithCpp:(const std::shared_ptr<::gearsbox::UserConfigGen>&)cppRef;

@end

@implementation GBUserConfigGen {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::gearsbox::UserConfigGen>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::gearsbox::UserConfigGen>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable GBConfigGen *)instance {
    try {
        auto r = ::gearsbox::UserConfigGen::instance();
        return ::djinni_generated::ConfigGen::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto UserConfigGen::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto UserConfigGen::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<GBUserConfigGen>(cpp);
}

}  // namespace djinni_generated

@end
