// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

#include "djinni_support.hpp"
#include "task_manager_gen.hpp"

namespace djinni_generated {

class NativeTaskManagerGen final : ::djinni::JniInterface<::gearsbox::TaskManagerGen, NativeTaskManagerGen> {
public:
    using CppType = std::shared_ptr<::gearsbox::TaskManagerGen>;
    using CppOptType = std::shared_ptr<::gearsbox::TaskManagerGen>;
    using JniType = jobject;

    using Boxed = NativeTaskManagerGen;

    ~NativeTaskManagerGen();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeTaskManagerGen>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeTaskManagerGen>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeTaskManagerGen();
    friend ::djinni::JniClass<NativeTaskManagerGen>;
    friend ::djinni::JniInterface<::gearsbox::TaskManagerGen, NativeTaskManagerGen>;

};

}  // namespace djinni_generated
