// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#include "NativePlatformExecutorGen.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativePlatformExecutorGen::NativePlatformExecutorGen() : ::djinni::JniInterface<::gearsbox::PlatformExecutorGen, NativePlatformExecutorGen>() {}

NativePlatformExecutorGen::~NativePlatformExecutorGen() = default;

NativePlatformExecutorGen::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativePlatformExecutorGen::JavaProxy::~JavaProxy() = default;

void NativePlatformExecutorGen::JavaProxy::endEniting(bool c_force) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativePlatformExecutorGen>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_endEniting,
                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c_force)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
