// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#include "NativeTyperConvertorDummy.hpp"  // my header
#include "NativeArgbColor.hpp"
#include "NativeConstraintType.hpp"
#include "NativeTextAlign.hpp"
#include "NativeTextBoarder.hpp"
#include "NativeTextKeyboard.hpp"
#include "NativeViewFrame.hpp"

namespace djinni_generated {

NativeTyperConvertorDummy::NativeTyperConvertorDummy() : ::djinni::JniInterface<::gearsbox::TyperConvertorDummy, NativeTyperConvertorDummy>() {}

NativeTyperConvertorDummy::~NativeTyperConvertorDummy() = default;

NativeTyperConvertorDummy::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeTyperConvertorDummy::JavaProxy::~JavaProxy() = default;

void NativeTyperConvertorDummy::JavaProxy::convertUIColor(const ::gearsbox::ArgbColor & c_color) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeTyperConvertorDummy>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_convertUIColor,
                           ::djinni::get(::djinni_generated::NativeArgbColor::fromCpp(jniEnv, c_color)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeTyperConvertorDummy::JavaProxy::convertUIRect(const ::gearsbox::ViewFrame & c_rect) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeTyperConvertorDummy>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_convertUIRect,
                           ::djinni::get(::djinni_generated::NativeViewFrame::fromCpp(jniEnv, c_rect)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeTyperConvertorDummy::JavaProxy::convertUIConstraintType(::gearsbox::ConstraintType c_type) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeTyperConvertorDummy>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_convertUIConstraintType,
                           ::djinni::get(::djinni_generated::NativeConstraintType::fromCpp(jniEnv, c_type)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeTyperConvertorDummy::JavaProxy::convertUITextBoarder(::gearsbox::TextBoarder c_type) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeTyperConvertorDummy>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_convertUITextBoarder,
                           ::djinni::get(::djinni_generated::NativeTextBoarder::fromCpp(jniEnv, c_type)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeTyperConvertorDummy::JavaProxy::convertUITextAlign(::gearsbox::TextAlign c_type) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeTyperConvertorDummy>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_convertUITextAlign,
                           ::djinni::get(::djinni_generated::NativeTextAlign::fromCpp(jniEnv, c_type)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeTyperConvertorDummy::JavaProxy::convertKeyboardType(::gearsbox::TextKeyboard c_type) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeTyperConvertorDummy>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_convertKeyboardType,
                           ::djinni::get(::djinni_generated::NativeTextKeyboard::fromCpp(jniEnv, c_type)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
