// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

#include "device_orientation.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeDeviceOrientation final : ::djinni::JniEnum {
public:
    using CppType = ::gearsbox::DeviceOrientation;
    using JniType = jobject;

    using Boxed = NativeDeviceOrientation;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeDeviceOrientation>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeDeviceOrientation>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeDeviceOrientation() : JniEnum("dyno/fun/gearsbox/DeviceOrientation") {}
    friend ::djinni::JniClass<NativeDeviceOrientation>;
};

}  // namespace djinni_generated
