// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#include "NativeTaskManagerGen.hpp"  // my header
#include "Marshal.hpp"
#include "NativeTaskGen.hpp"
#include "NativeTaskManagerGen.hpp"

namespace djinni_generated {

NativeTaskManagerGen::NativeTaskManagerGen() : ::djinni::JniInterface<::gearsbox::TaskManagerGen, NativeTaskManagerGen>("dyno/fun/gearsbox/TaskManagerGen$CppProxy") {}

NativeTaskManagerGen::~NativeTaskManagerGen() = default;


CJNIEXPORT void JNICALL Java_dyno_fun_gearsbox_TaskManagerGen_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::gearsbox::TaskManagerGen>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_dyno_fun_gearsbox_TaskManagerGen_instance(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::gearsbox::TaskManagerGen::instance();
        return ::djinni::release(::djinni_generated::NativeTaskManagerGen::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_dyno_fun_gearsbox_TaskManagerGen_00024CppProxy_native_1addTask(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_task)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::gearsbox::TaskManagerGen>(nativeRef);
        ref->addTask(::djinni_generated::NativeTaskGen::toCpp(jniEnv, j_task));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_dyno_fun_gearsbox_TaskManagerGen_00024CppProxy_native_1addDelayTask(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jlong j_delay, jlong j_repeated)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::gearsbox::TaskManagerGen>(nativeRef);
        ref->addDelayTask(::djinni::I64::toCpp(jniEnv, j_delay),
                          ::djinni::I64::toCpp(jniEnv, j_repeated));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
