// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#include "NativeTimerHandlerGen.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeTimerHandlerGen::NativeTimerHandlerGen() : ::djinni::JniInterface<::gearsbox::TimerHandlerGen, NativeTimerHandlerGen>("dyno/fun/gearsbox/TimerHandlerGen$CppProxy") {}

NativeTimerHandlerGen::~NativeTimerHandlerGen() = default;

NativeTimerHandlerGen::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeTimerHandlerGen::JavaProxy::~JavaProxy() = default;

void NativeTimerHandlerGen::JavaProxy::handler(int64_t c_time_passed, int32_t c_repeated) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeTimerHandlerGen>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_handler,
                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c_time_passed)),
                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c_repeated)));
    ::djinni::jniExceptionCheck(jniEnv);
}

CJNIEXPORT void JNICALL Java_dyno_fun_gearsbox_TimerHandlerGen_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::gearsbox::TimerHandlerGen>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_dyno_fun_gearsbox_TimerHandlerGen_00024CppProxy_native_1handler(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jlong j_timePassed, jint j_repeated)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::gearsbox::TimerHandlerGen>(nativeRef);
        ref->handler(::djinni::I64::toCpp(jniEnv, j_timePassed),
                     ::djinni::I32::toCpp(jniEnv, j_repeated));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
