// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#pragma once

#include "camera_flash.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeCameraFlash final : ::djinni::JniEnum {
public:
    using CppType = ::gearsbox::CameraFlash;
    using JniType = jobject;

    using Boxed = NativeCameraFlash;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeCameraFlash>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeCameraFlash>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeCameraFlash() : JniEnum("dyno/fun/gearsbox/CameraFlash") {}
    friend ::djinni::JniClass<NativeCameraFlash>;
};

}  // namespace djinni_generated
