// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#pragma once

#include "camera_quality.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeCameraQuality final : ::djinni::JniEnum {
public:
    using CppType = ::gearsbox::CameraQuality;
    using JniType = jobject;

    using Boxed = NativeCameraQuality;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeCameraQuality>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeCameraQuality>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeCameraQuality() : JniEnum("dyno/fun/gearsbox/CameraQuality") {}
    friend ::djinni::JniClass<NativeCameraQuality>;
};

}  // namespace djinni_generated
