// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#include "NativeVideoWriterResultHandler.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeVideoWriterResultHandler::NativeVideoWriterResultHandler() : ::djinni::JniInterface<::gearsbox::VideoWriterResultHandler, NativeVideoWriterResultHandler>("dyno/fun/gearsbox/VideoWriterResultHandler$CppProxy") {}

NativeVideoWriterResultHandler::~NativeVideoWriterResultHandler() = default;

NativeVideoWriterResultHandler::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeVideoWriterResultHandler::JavaProxy::~JavaProxy() = default;

void NativeVideoWriterResultHandler::JavaProxy::onComplete(bool c_success, const std::string & c_path, int32_t c_duration) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeVideoWriterResultHandler>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onComplete,
                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c_success)),
                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c_path)),
                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c_duration)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeVideoWriterResultHandler::JavaProxy::beforeComplete() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeVideoWriterResultHandler>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_beforeComplete);
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeVideoWriterResultHandler::JavaProxy::onProgress(float c_percent) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeVideoWriterResultHandler>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onProgress,
                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c_percent)));
    ::djinni::jniExceptionCheck(jniEnv);
}

CJNIEXPORT void JNICALL Java_dyno_fun_gearsbox_VideoWriterResultHandler_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::gearsbox::VideoWriterResultHandler>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_dyno_fun_gearsbox_VideoWriterResultHandler_00024CppProxy_native_1onComplete(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jboolean j_success, jstring j_path, jint j_duration)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::gearsbox::VideoWriterResultHandler>(nativeRef);
        ref->onComplete(::djinni::Bool::toCpp(jniEnv, j_success),
                        ::djinni::String::toCpp(jniEnv, j_path),
                        ::djinni::I32::toCpp(jniEnv, j_duration));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_dyno_fun_gearsbox_VideoWriterResultHandler_00024CppProxy_native_1beforeComplete(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::gearsbox::VideoWriterResultHandler>(nativeRef);
        ref->beforeComplete();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_dyno_fun_gearsbox_VideoWriterResultHandler_00024CppProxy_native_1onProgress(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jfloat j_percent)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::gearsbox::VideoWriterResultHandler>(nativeRef);
        ref->onProgress(::djinni::F32::toCpp(jniEnv, j_percent));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
