// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#include "NativePlatformUtilityGen.hpp"  // my header
#include "NativePlatformExecutorGen.hpp"
#include "NativePlatformUtilityGen.hpp"

namespace djinni_generated {

NativePlatformUtilityGen::NativePlatformUtilityGen() : ::djinni::JniInterface<::gearsbox::PlatformUtilityGen, NativePlatformUtilityGen>("dyno/fun/gearsbox/PlatformUtilityGen$CppProxy") {}

NativePlatformUtilityGen::~NativePlatformUtilityGen() = default;


CJNIEXPORT void JNICALL Java_dyno_fun_gearsbox_PlatformUtilityGen_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::gearsbox::PlatformUtilityGen>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_dyno_fun_gearsbox_PlatformUtilityGen_instance(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::gearsbox::PlatformUtilityGen::instance();
        return ::djinni::release(::djinni_generated::NativePlatformUtilityGen::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_dyno_fun_gearsbox_PlatformUtilityGen_00024CppProxy_native_1setPlatofrmExcutor(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_excuser)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::gearsbox::PlatformUtilityGen>(nativeRef);
        ref->setPlatofrmExcutor(::djinni_generated::NativePlatformExecutorGen::toCpp(jniEnv, j_excuser));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_dyno_fun_gearsbox_PlatformUtilityGen_00024CppProxy_native_1getExcutor(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::gearsbox::PlatformUtilityGen>(nativeRef);
        auto r = ref->getExcutor();
        return ::djinni::release(::djinni_generated::NativePlatformExecutorGen::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
