// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#include "NativeCrashHandlerGen.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeCrashHandlerGen::NativeCrashHandlerGen() : ::djinni::JniInterface<::gearsbox::CrashHandlerGen, NativeCrashHandlerGen>("dyno/fun/gearsbox/CrashHandlerGen$CppProxy") {}

NativeCrashHandlerGen::~NativeCrashHandlerGen() = default;


CJNIEXPORT void JNICALL Java_dyno_fun_gearsbox_CrashHandlerGen_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::gearsbox::CrashHandlerGen>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_dyno_fun_gearsbox_CrashHandlerGen_00024CppProxy_native_1header(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_path, jstring j_url)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::gearsbox::CrashHandlerGen>(nativeRef);
        ref->header(::djinni::String::toCpp(jniEnv, j_path),
                    ::djinni::String::toCpp(jniEnv, j_url));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
