// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#include "NativeDuration.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeDuration::NativeDuration() = default;

NativeDuration::~NativeDuration() = default;

auto NativeDuration::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeDuration>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.value)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.scale)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeDuration::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeDuration>::get();
    return {::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mValue)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mScale))};
}

}  // namespace djinni_generated
