// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#pragma once

#include "camera_config_gen.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeCameraConfigGen final : ::djinni::JniInterface<::gearsbox::CameraConfigGen, NativeCameraConfigGen> {
public:
    using CppType = std::shared_ptr<::gearsbox::CameraConfigGen>;
    using CppOptType = std::shared_ptr<::gearsbox::CameraConfigGen>;
    using JniType = jobject;

    using Boxed = NativeCameraConfigGen;

    ~NativeCameraConfigGen();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeCameraConfigGen>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeCameraConfigGen>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeCameraConfigGen();
    friend ::djinni::JniClass<NativeCameraConfigGen>;
    friend ::djinni::JniInterface<::gearsbox::CameraConfigGen, NativeCameraConfigGen>;

};

}  // namespace djinni_generated
