// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#pragma once

#include "djinni_support.hpp"
#include "video_frame_gen.hpp"

namespace djinni_generated {

class NativeVideoFrameGen final : ::djinni::JniInterface<::gearsbox::VideoFrameGen, NativeVideoFrameGen> {
public:
    using CppType = std::shared_ptr<::gearsbox::VideoFrameGen>;
    using CppOptType = std::shared_ptr<::gearsbox::VideoFrameGen>;
    using JniType = jobject;

    using Boxed = NativeVideoFrameGen;

    ~NativeVideoFrameGen();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeVideoFrameGen>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeVideoFrameGen>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeVideoFrameGen();
    friend ::djinni::JniClass<NativeVideoFrameGen>;
    friend ::djinni::JniInterface<::gearsbox::VideoFrameGen, NativeVideoFrameGen>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::gearsbox::VideoFrameGen
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        bool parserSample() override;
        int64_t getData() override;
        int32_t getWidth() override;
        int32_t getHeight() override;
        int64_t getSize() override;
        int32_t getLineSize() override;
        void setData(int64_t data) override;
        void setWidth(int32_t width) override;
        void setHeight(int32_t height) override;
        void setSize(int64_t size) override;
        void setLineSize(int32_t linesize) override;
        int64_t getAudioData() override;
        int64_t getAudioDataSize() override;
        int64_t getAudioPSTValue() override;
        int32_t getAudioPSTScale() override;
        int32_t getNumSamples() override;
        int32_t getChannelsPerFrame() override;
        double getSampleRate() override;
        int32_t getBitsPerChannel() override;
        void setAudioData(int64_t data) override;
        void setAudioDataSize(int64_t size) override;
        void setAudioPSTValue(int64_t value) override;
        void setAudioPSTScale(int32_t scale) override;
        void setNumSamples(int32_t num) override;
        void setChannelsPerFrame(int32_t channels) override;
        void setSampleRate(double rate) override;
        void setBitsPerChannel(int32_t bits) override;

    private:
        friend ::djinni::JniInterface<::gearsbox::VideoFrameGen, ::djinni_generated::NativeVideoFrameGen>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("dyno/fun/gearsbox/VideoFrameGen") };
    const jmethodID method_parserSample { ::djinni::jniGetMethodID(clazz.get(), "parserSample", "()Z") };
    const jmethodID method_getData { ::djinni::jniGetMethodID(clazz.get(), "getData", "()J") };
    const jmethodID method_getWidth { ::djinni::jniGetMethodID(clazz.get(), "getWidth", "()I") };
    const jmethodID method_getHeight { ::djinni::jniGetMethodID(clazz.get(), "getHeight", "()I") };
    const jmethodID method_getSize { ::djinni::jniGetMethodID(clazz.get(), "getSize", "()J") };
    const jmethodID method_getLineSize { ::djinni::jniGetMethodID(clazz.get(), "getLineSize", "()I") };
    const jmethodID method_setData { ::djinni::jniGetMethodID(clazz.get(), "setData", "(J)V") };
    const jmethodID method_setWidth { ::djinni::jniGetMethodID(clazz.get(), "setWidth", "(I)V") };
    const jmethodID method_setHeight { ::djinni::jniGetMethodID(clazz.get(), "setHeight", "(I)V") };
    const jmethodID method_setSize { ::djinni::jniGetMethodID(clazz.get(), "setSize", "(J)V") };
    const jmethodID method_setLineSize { ::djinni::jniGetMethodID(clazz.get(), "setLineSize", "(I)V") };
    const jmethodID method_getAudioData { ::djinni::jniGetMethodID(clazz.get(), "getAudioData", "()J") };
    const jmethodID method_getAudioDataSize { ::djinni::jniGetMethodID(clazz.get(), "getAudioDataSize", "()J") };
    const jmethodID method_getAudioPSTValue { ::djinni::jniGetMethodID(clazz.get(), "getAudioPSTValue", "()J") };
    const jmethodID method_getAudioPSTScale { ::djinni::jniGetMethodID(clazz.get(), "getAudioPSTScale", "()I") };
    const jmethodID method_getNumSamples { ::djinni::jniGetMethodID(clazz.get(), "getNumSamples", "()I") };
    const jmethodID method_getChannelsPerFrame { ::djinni::jniGetMethodID(clazz.get(), "getChannelsPerFrame", "()I") };
    const jmethodID method_getSampleRate { ::djinni::jniGetMethodID(clazz.get(), "getSampleRate", "()D") };
    const jmethodID method_getBitsPerChannel { ::djinni::jniGetMethodID(clazz.get(), "getBitsPerChannel", "()I") };
    const jmethodID method_setAudioData { ::djinni::jniGetMethodID(clazz.get(), "setAudioData", "(J)V") };
    const jmethodID method_setAudioDataSize { ::djinni::jniGetMethodID(clazz.get(), "setAudioDataSize", "(J)V") };
    const jmethodID method_setAudioPSTValue { ::djinni::jniGetMethodID(clazz.get(), "setAudioPSTValue", "(J)V") };
    const jmethodID method_setAudioPSTScale { ::djinni::jniGetMethodID(clazz.get(), "setAudioPSTScale", "(I)V") };
    const jmethodID method_setNumSamples { ::djinni::jniGetMethodID(clazz.get(), "setNumSamples", "(I)V") };
    const jmethodID method_setChannelsPerFrame { ::djinni::jniGetMethodID(clazz.get(), "setChannelsPerFrame", "(I)V") };
    const jmethodID method_setSampleRate { ::djinni::jniGetMethodID(clazz.get(), "setSampleRate", "(D)V") };
    const jmethodID method_setBitsPerChannel { ::djinni::jniGetMethodID(clazz.get(), "setBitsPerChannel", "(I)V") };
};

}  // namespace djinni_generated
