// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#include "NativeArgbColor.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeArgbColor::NativeArgbColor() = default;

NativeArgbColor::~NativeArgbColor() = default;

auto NativeArgbColor::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeArgbColor>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.a)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.r)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.g)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.b)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeArgbColor::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 5);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeArgbColor>::get();
    return {::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_mA)),
            ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_mR)),
            ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_mG)),
            ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_mB))};
}

}  // namespace djinni_generated
