// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from config.djinni

#pragma once

#include "config_gen.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeConfigGen final : ::djinni::JniInterface<::gearsbox::ConfigGen, NativeConfigGen> {
public:
    using CppType = std::shared_ptr<::gearsbox::ConfigGen>;
    using CppOptType = std::shared_ptr<::gearsbox::ConfigGen>;
    using JniType = jobject;

    using Boxed = NativeConfigGen;

    ~NativeConfigGen();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeConfigGen>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeConfigGen>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeConfigGen();
    friend ::djinni::JniClass<NativeConfigGen>;
    friend ::djinni::JniInterface<::gearsbox::ConfigGen, NativeConfigGen>;

};

}  // namespace djinni_generated
