// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#include "NativeVideoFrameGen.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeVideoFrameGen::NativeVideoFrameGen() : ::djinni::JniInterface<::gearsbox::VideoFrameGen, NativeVideoFrameGen>() {}

NativeVideoFrameGen::~NativeVideoFrameGen() = default;

NativeVideoFrameGen::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeVideoFrameGen::JavaProxy::~JavaProxy() = default;

int64_t NativeVideoFrameGen::JavaProxy::getData() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeVideoFrameGen>::get();
    auto jret = jniEnv->CallLongMethod(Handle::get().get(), data.method_getData);
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni::I64::toCpp(jniEnv, jret);
}
int32_t NativeVideoFrameGen::JavaProxy::getWidth() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeVideoFrameGen>::get();
    auto jret = jniEnv->CallIntMethod(Handle::get().get(), data.method_getWidth);
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni::I32::toCpp(jniEnv, jret);
}
int32_t NativeVideoFrameGen::JavaProxy::getHeight() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeVideoFrameGen>::get();
    auto jret = jniEnv->CallIntMethod(Handle::get().get(), data.method_getHeight);
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni::I32::toCpp(jniEnv, jret);
}
int64_t NativeVideoFrameGen::JavaProxy::getSize() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeVideoFrameGen>::get();
    auto jret = jniEnv->CallLongMethod(Handle::get().get(), data.method_getSize);
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni::I64::toCpp(jniEnv, jret);
}
int32_t NativeVideoFrameGen::JavaProxy::getLineSize() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeVideoFrameGen>::get();
    auto jret = jniEnv->CallIntMethod(Handle::get().get(), data.method_getLineSize);
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni::I32::toCpp(jniEnv, jret);
}
void NativeVideoFrameGen::JavaProxy::setData(int64_t c_data) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeVideoFrameGen>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_setData,
                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c_data)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeVideoFrameGen::JavaProxy::setWidth(int32_t c_width) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeVideoFrameGen>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_setWidth,
                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c_width)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeVideoFrameGen::JavaProxy::setHeight(int32_t c_height) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeVideoFrameGen>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_setHeight,
                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c_height)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeVideoFrameGen::JavaProxy::setSize(int64_t c_size) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeVideoFrameGen>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_setSize,
                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c_size)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeVideoFrameGen::JavaProxy::setLineSize(int32_t c_linesize) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeVideoFrameGen>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_setLineSize,
                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c_linesize)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
