// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#pragma once

#include "camera_focus_mode.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeCameraFocusMode final : ::djinni::JniEnum {
public:
    using CppType = ::gearsbox::CameraFocusMode;
    using JniType = jobject;

    using Boxed = NativeCameraFocusMode;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeCameraFocusMode>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeCameraFocusMode>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeCameraFocusMode() : JniEnum("dyno/fun/gearsbox/CameraFocusMode") {}
    friend ::djinni::JniClass<NativeCameraFocusMode>;
};

}  // namespace djinni_generated
