// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#pragma once

#include "camera_capture_mode.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeCameraCaptureMode final : ::djinni::JniEnum {
public:
    using CppType = ::gearsbox::CameraCaptureMode;
    using JniType = jobject;

    using Boxed = NativeCameraCaptureMode;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeCameraCaptureMode>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeCameraCaptureMode>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeCameraCaptureMode() : JniEnum("dyno/fun/gearsbox/CameraCaptureMode") {}
    friend ::djinni::JniClass<NativeCameraCaptureMode>;
};

}  // namespace djinni_generated
