// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

#include "djinni_support.hpp"
#include "language_store_gen.hpp"

namespace djinni_generated {

class NativeLanguageStoreGen final : ::djinni::JniInterface<::gearsbox::LanguageStoreGen, NativeLanguageStoreGen> {
public:
    using CppType = std::shared_ptr<::gearsbox::LanguageStoreGen>;
    using CppOptType = std::shared_ptr<::gearsbox::LanguageStoreGen>;
    using JniType = jobject;

    using Boxed = NativeLanguageStoreGen;

    ~NativeLanguageStoreGen();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeLanguageStoreGen>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeLanguageStoreGen>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeLanguageStoreGen();
    friend ::djinni::JniClass<NativeLanguageStoreGen>;
    friend ::djinni::JniInterface<::gearsbox::LanguageStoreGen, NativeLanguageStoreGen>;

};

}  // namespace djinni_generated
