// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#pragma once

#include "camera_focus_range.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeCameraFocusRange final : ::djinni::JniEnum {
public:
    using CppType = ::gearsbox::CameraFocusRange;
    using JniType = jobject;

    using Boxed = NativeCameraFocusRange;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeCameraFocusRange>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeCameraFocusRange>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeCameraFocusRange() : JniEnum("dyno/fun/gearsbox/CameraFocusRange") {}
    friend ::djinni::JniClass<NativeCameraFocusRange>;
};

}  // namespace djinni_generated
