// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

#include "djinni_support.hpp"
#include "user_config_gen.hpp"

namespace djinni_generated {

class NativeUserConfigGen final : ::djinni::JniInterface<::gearsbox::UserConfigGen, NativeUserConfigGen> {
public:
    using CppType = std::shared_ptr<::gearsbox::UserConfigGen>;
    using CppOptType = std::shared_ptr<::gearsbox::UserConfigGen>;
    using JniType = jobject;

    using Boxed = NativeUserConfigGen;

    ~NativeUserConfigGen();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeUserConfigGen>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeUserConfigGen>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeUserConfigGen();
    friend ::djinni::JniClass<NativeUserConfigGen>;
    friend ::djinni::JniInterface<::gearsbox::UserConfigGen, NativeUserConfigGen>;

};

}  // namespace djinni_generated
