// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

#include "djinni_support.hpp"
#include "task_gen.hpp"

namespace djinni_generated {

class NativeTaskGen final : ::djinni::JniInterface<::gearsbox::TaskGen, NativeTaskGen> {
public:
    using CppType = std::shared_ptr<::gearsbox::TaskGen>;
    using CppOptType = std::shared_ptr<::gearsbox::TaskGen>;
    using JniType = jobject;

    using Boxed = NativeTaskGen;

    ~NativeTaskGen();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeTaskGen>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeTaskGen>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeTaskGen();
    friend ::djinni::JniClass<NativeTaskGen>;
    friend ::djinni::JniInterface<::gearsbox::TaskGen, NativeTaskGen>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::gearsbox::TaskGen
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void excuse(const ::gearsbox::TaskInfo & info) override;

    private:
        friend ::djinni::JniInterface<::gearsbox::TaskGen, ::djinni_generated::NativeTaskGen>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("dyno/fun/gearsbox/TaskGen") };
    const jmethodID method_excuse { ::djinni::jniGetMethodID(clazz.get(), "excuse", "(Ldyno/fun/gearsbox/TaskInfo;)V") };
};

}  // namespace djinni_generated
