// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#pragma once

#include "camera_exposure_mode.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeCameraExposureMode final : ::djinni::JniEnum {
public:
    using CppType = ::gearsbox::CameraExposureMode;
    using JniType = jobject;

    using Boxed = NativeCameraExposureMode;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeCameraExposureMode>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeCameraExposureMode>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeCameraExposureMode() : JniEnum("dyno/fun/gearsbox/CameraExposureMode") {}
    friend ::djinni::JniClass<NativeCameraExposureMode>;
};

}  // namespace djinni_generated
