// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#import <Foundation/Foundation.h>
@class GBTestMgrGen;


@interface GBTestMgrGen : NSObject

+ (nullable GBTestMgrGen *)instance;

- (BOOL)initialize:(nonnull NSString *)selfPath;

- (int32_t)runTests;

@end
