// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

package dyno.fun.gearsbox;

public abstract class CameraControllerGen {
    public abstract void startCamera();

    public abstract void stopCamera();

    public abstract void setFlash(CameraFlash mode);

    public abstract void setQuality(CameraQuality quality);

    public abstract void switchFront(boolean front);

    public abstract boolean isFront();

    public abstract CameraFlash getFlash();

    public abstract CameraQuality getQuality();

    public abstract void setFousePoint(int x, int y);

    public abstract void setExposurePoint(int x, int y);

    public abstract void setZoom(float zoom);

    public abstract float getZoom();

    public abstract void setISO(int iso);

    public abstract int getISO();

    public abstract void setShutter(int shutter);

    public abstract int getShutter();

    public abstract void setAperture(float f);

    public abstract float getAperture();

    public abstract VideoFrameGen captureOneFrame();
}
