// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

package dyno.fun.gearsbox;

public enum CameraQuality {
    LOW,
    MEDIUM,
    HIGH,
    PESETPHOTO,
    ;
}
