// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

package dyno.fun.gearsbox;

/**@import "ui.djinni" */
public enum CameraFlash {
    ON,
    OFF,
    AUTO,
    ;
}
