// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

package dyno.fun.gearsbox;

public enum CameraExposureMode {
    NONE,
    /** ios Indicates that the exposure should be locked at its current value. */
    LOCKED,
    /** ios Indicates that the device should automatically adjust exposure once and then change the exposure mode to Locked. */
    AUTOEXPOSE,
    /** ios Indicates that the device should automatically adjust exposure when needed. */
    CONTINUOUSAUTOEXPOSURE,
    /**ios Indicates that the device should only adjust exposure according to user provided ISO, exposureDuration values. */
    MODECUSTOM,
    ;
}
