// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

package dyno.fun.gearsbox;

public enum DeviceOrientation {
    UNKNOWN,
    PORTRAIT,
    PROTRAIT_DOWN,
    LANDSCAPE_LEFT,
    LANDSCAPE_RIGHT,
    FACEUP,
    FACEDOWN,
    ;
}
