// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

package dyno.fun.gearsbox;

public abstract class DeviceGen {
    public abstract DeviceOrientation getOrientation();

    public abstract String getID();
}
