// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

package dyno.fun.gearsbox;

public abstract class PlatformUtilityGen {
    public abstract void endEniting(boolean force);

    /**ios home directory */
    public abstract String getHomeDirectory();

    public abstract String getPackFilePath(String file);

    public abstract String getPackFileBuffer(String file);

    /**copy pack file to home directory and return path in home directory */
    public abstract String getPackFileToHomePath(String file);
}
