// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

package dyno.fun.gearsbox;

public abstract class PlatformUtilityGen {
    public abstract void endEniting(boolean force);

    public abstract String getRootDirectory();

    public abstract String getPackFilePath(String file);
}
