// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

package dyno.fun.gearsbox;

public final class TaskInfo {


    /*package*/ final long mDelay;

    /*package*/ final boolean mRepeate;

    public TaskInfo(
            long delay,
            boolean repeate) {
        this.mDelay = delay;
        this.mRepeate = repeate;
    }

    public long getDelay() {
        return mDelay;
    }

    public boolean getRepeate() {
        return mRepeate;
    }

    @Override
    public String toString() {
        return "TaskInfo{" +
                "mDelay=" + mDelay +
                "," + "mRepeate=" + mRepeate +
        "}";
    }

}
