// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

package dyno.fun.gearsbox;

public final class TaskInfo {


    /*package*/ final long mTarskId;

    /*package*/ final long mDelay;

    /*package*/ final int mRepeated;

    /*package*/ final long mElapsed;

    public TaskInfo(
            long tarskId,
            long delay,
            int repeated,
            long elapsed) {
        this.mTarskId = tarskId;
        this.mDelay = delay;
        this.mRepeated = repeated;
        this.mElapsed = elapsed;
    }

    public long getTarskId() {
        return mTarskId;
    }

    public long getDelay() {
        return mDelay;
    }

    public int getRepeated() {
        return mRepeated;
    }

    public long getElapsed() {
        return mElapsed;
    }

    @Override
    public String toString() {
        return "TaskInfo{" +
                "mTarskId=" + mTarskId +
                "," + "mDelay=" + mDelay +
                "," + "mRepeated=" + mRepeated +
                "," + "mElapsed=" + mElapsed +
        "}";
    }

}
