// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

package dyno.fun.gearsbox;

public enum TextKeyboard {
    DEFAULT,
    ASCII,
    URL,
    NUMBERPAD,
    PHONEPAD,
    DECIMALPAD,
    ;
}
