// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

package dyno.fun.gearsbox;

public abstract class TyperConvertor {
    public abstract void convertUIColor(ArgbColor color);

    public abstract void convertUIRect(ViewFrame rect);

    public abstract void convertUIConstraintType(ConstraintType type);

    public abstract void convertUITextBoarder(TextBoarder type);

    public abstract void convertUITextAlign(TextAlign type);
}
