// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

package dyno.fun.gearsbox;

public enum VideoOrientation {
    LANDSPACE_0,
    LANDSPACE_180,
    PORTRAIT_90,
    PORTRAIT_270,
    ;
}
