// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

package dyno.fun.gearsbox;

public abstract class ViewFactoryGen {
    public abstract ViewGen createView(ViewConf conf);

    public abstract ViewGen createViewById(String id, ViewType type);

    public abstract boolean injectView(ViewGen view);

    public abstract void showViewController(String id, boolean animated);
}
