// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

package dyno.fun.gearsbox;

public abstract class ViewGen {
    public static final int NUMBER_INT = 1;

    public static final int NUMBER_FLOAT = 2;

    public static final int NUMBER_POSITIVE = 4;

    public static final int NUMBER_NEGATIVE = 8;

    public abstract String getId();

    public abstract void setFrame(ViewFrame frame);

    public abstract ViewFrame getFrame();

    public abstract void setBackgroundColor(float a, float r, float g, float b);

    public abstract void setVisiable(boolean v);

    public abstract ViewType getType();

    public abstract void setBoard(float width, ArgbColor color);

    public abstract void setText(String text);

    public abstract String getText();

    public abstract void setTextColor(ArgbColor color);

    public abstract void setFontSize(int size);

    public abstract void setNumbernic(int type);

    public abstract void setMaxTextLen(int length);

    public abstract ViewGen getSubView(String id);

    public abstract ViewGen addSubViewById(String id, ViewType type);

    public abstract ViewGen addSubView(ViewConf conf);

    public abstract boolean removeSubView(String id);

    public abstract void removeAllSubView();

    public abstract void addConstraint(ViewConstraint constraint);

    public abstract void setEventHandler(ViewEvent event, ViewEventHandler handler);
}
