// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#include "argb_color.hpp"  // my header

namespace gearsbox {

ArgbColor const ArgbColor::NOCOLOR = ArgbColor(
    0 /* a */ ,
    0 /* r */ ,
    0 /* g */ ,
    0 /* b */ );

ArgbColor const ArgbColor::REDCOLOR = ArgbColor(
    1 /* a */ ,
    1 /* r */ ,
    0 /* g */ ,
    0 /* b */ );

ArgbColor const ArgbColor::GREENCOLOR = ArgbColor(
    1 /* a */ ,
    0 /* r */ ,
    1 /* g */ ,
    0 /* b */ );

ArgbColor const ArgbColor::BLUECOLOR = ArgbColor(
    1 /* a */ ,
    0 /* r */ ,
    0 /* g */ ,
    1 /* b */ );

ArgbColor const ArgbColor::BLACKCOLOR = ArgbColor(
    1 /* a */ ,
    0 /* r */ ,
    0 /* g */ ,
    0 /* b */ );

ArgbColor const ArgbColor::WHITECOLOR = ArgbColor(
    1 /* a */ ,
    1 /* r */ ,
    1 /* g */ ,
    1 /* b */ );

}  // namespace gearsbox
