// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>

namespace gearsbox {

class TestMgrGen {
public:
    virtual ~TestMgrGen() {}

    static std::shared_ptr<TestMgrGen> instance();

    virtual bool initialize(const std::string & self_path) = 0;

    virtual int32_t runTests() = 0;
};

}  // namespace gearsbox
