// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include <functional>

namespace gearsbox {

enum class TextAlign : int {
    NONE,
    LEFT,
    CENTER,
    RIGHT,
};

}  // namespace gearsbox

namespace std {

template <>
struct hash<::gearsbox::TextAlign> {
    size_t operator()(::gearsbox::TextAlign type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
