// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

#include <memory>

namespace gearsbox {

class ConfigGen;

class UserConfigGen {
public:
    virtual ~UserConfigGen() {}

    static std::shared_ptr<ConfigGen> instance();
};

}  // namespace gearsbox
