// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include "constraint_type.hpp"
#include <string>
#include <utility>

namespace gearsbox {

struct ViewConstraint; // Requiring extended class

struct ViewConstraintBase {

    static std::string const SELF;
    ConstraintType type;
    ConstraintType type_to;
    std::string view_from;
    std::string view_to;
    float multiplier;
    float offset;

    ViewConstraintBase(ConstraintType type_,
                       ConstraintType type_to_,
                       std::string view_from_,
                       std::string view_to_,
                       float multiplier_,
                       float offset_)
    : type(std::move(type_))
    , type_to(std::move(type_to_))
    , view_from(std::move(view_from_))
    , view_to(std::move(view_to_))
    , multiplier(std::move(multiplier_))
    , offset(std::move(offset_))
    {}

    virtual ~ViewConstraintBase() = default;

protected:
    ViewConstraintBase(const ViewConstraintBase&) = default;
    ViewConstraintBase(ViewConstraintBase&&) = default;
    ViewConstraintBase& operator=(const ViewConstraintBase&) = default;
    ViewConstraintBase& operator=(ViewConstraintBase&&) = default;
};

}  // namespace gearsbox
