// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

package dyno.fun.gearsbox;

public abstract class PlatformExecutorGen {
    public abstract void endEniting(boolean force);
}
