// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

package dyno.fun.gearsbox;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class PlatformUtilityGen {
    public abstract void setPlatofrmExcutor(PlatformExecutorGen excuser);

    public abstract PlatformExecutorGen getExcutor();

    public static native PlatformUtilityGen instance();

    private static final class CppProxy extends PlatformUtilityGen
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public void setPlatofrmExcutor(PlatformExecutorGen excuser)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setPlatofrmExcutor(this.nativeRef, excuser);
        }
        private native void native_setPlatofrmExcutor(long _nativeRef, PlatformExecutorGen excuser);

        @Override
        public PlatformExecutorGen getExcutor()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getExcutor(this.nativeRef);
        }
        private native PlatformExecutorGen native_getExcutor(long _nativeRef);
    }
}
