// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import "GBArgbColor.h"


@implementation GBArgbColor

- (nonnull instancetype)initWithA:(float)a
                                r:(float)r
                                g:(float)g
                                b:(float)b
{
    if (self = [super init]) {
        _a = a;
        _r = r;
        _g = g;
        _b = b;
    }
    return self;
}

+ (nonnull instancetype)argbColorWithA:(float)a
                                     r:(float)r
                                     g:(float)g
                                     b:(float)b
{
    return [[self alloc] initWithA:a
                                 r:r
                                 g:g
                                 b:b];
}

+ (GBArgbColor * __nonnull)noColor
{
    static GBArgbColor * const s_noColor = [[GBArgbColor alloc] initWithA:0
            r:0
            g:0
            b:0];
    return s_noColor;
}

+ (GBArgbColor * __nonnull)redColor
{
    static GBArgbColor * const s_redColor = [[GBArgbColor alloc] initWithA:1
            r:1
            g:0
            b:0];
    return s_redColor;
}

+ (GBArgbColor * __nonnull)greenColor
{
    static GBArgbColor * const s_greenColor = [[GBArgbColor alloc] initWithA:1
            r:0
            g:1
            b:0];
    return s_greenColor;
}

+ (GBArgbColor * __nonnull)blueColor
{
    static GBArgbColor * const s_blueColor = [[GBArgbColor alloc] initWithA:1
            r:0
            g:0
            b:1];
    return s_blueColor;
}

+ (GBArgbColor * __nonnull)blackColor
{
    static GBArgbColor * const s_blackColor = [[GBArgbColor alloc] initWithA:1
            r:0
            g:0
            b:0];
    return s_blackColor;
}

+ (GBArgbColor * __nonnull)whiteColor
{
    static GBArgbColor * const s_whiteColor = [[GBArgbColor alloc] initWithA:1
            r:1
            g:1
            b:1];
    return s_whiteColor;
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p a:%@ r:%@ g:%@ b:%@>", self.class, (void *)self, @(self.a), @(self.r), @(self.g), @(self.b)];
}

@end
