// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#import "GBCameraFlash.h"
#import "GBCameraQuality.h"
#import <Foundation/Foundation.h>
@class GBCameraConfigGen;
@class GBConfigGen;

extern NSString * __nonnull const GBCameraConfigGenFlashMode;
extern NSString * __nonnull const GBCameraConfigGenFlashModeAuto;
extern NSString * __nonnull const GBCameraConfigGenFlashModeOn;
extern NSString * __nonnull const GBCameraConfigGenFlashModeOff;
extern NSString * __nonnull const GBCameraConfigGenQuality;
extern NSString * __nonnull const GBCameraConfigGenQuality360p;
extern NSString * __nonnull const GBCameraConfigGenQuality480p;
extern NSString * __nonnull const GBCameraConfigGenQuality720p;
extern NSString * __nonnull const GBCameraConfigGenQuality1080p;

@interface GBCameraConfigGen : NSObject

+ (nullable GBCameraConfigGen *)instance;

- (BOOL)initialize:(nullable GBConfigGen *)cfg;

- (GBCameraFlash)getFlashMode;

- (GBCameraQuality)getQuatityLevel;

- (void)setFlashMode:(GBCameraFlash)mode;

- (void)setQuatityLevel:(GBCameraQuality)quality;

@end
