// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#import "GBCameraFlash.h"
#import "GBCameraQuality.h"
#import <Foundation/Foundation.h>
@protocol GBVideoFrameGen;


@protocol GBCameraControllerGen

- (void)startCamera;

- (void)stopCamera;

- (void)setFlash:(GBCameraFlash)mode;

- (void)setQuality:(GBCameraQuality)quality;

- (void)switchFront:(BOOL)front;

- (BOOL)isFront;

- (GBCameraFlash)getFlash;

- (GBCameraQuality)getQuality;

- (void)setFousePoint:(int32_t)x
                    y:(int32_t)y;

- (void)setExposurePoint:(int32_t)x
                       y:(int32_t)y;

- (void)setZoom:(float)zoom;

- (float)getZoom;

- (void)setISO:(int32_t)iso;

- (int32_t)getISO;

- (void)setShutter:(int32_t)shutter;

- (int32_t)getShutter;

- (void)setAperture:(float)f;

- (float)getAperture;

- (nullable id<GBVideoFrameGen>)captureOneFrame;

@end
