// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, GBCameraFocusMode)
{
    GBCameraFocusModeNone,
    GBCameraFocusModeLocked,
    GBCameraFocusModeAutoFocus,
    GBCameraFocusModeContinuousAutoFocus,
};
