// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#import "GBCameraCaptureMode.h"
#import "GBCameraExposureMode.h"
#import "GBCameraFlash.h"
#import "GBCameraFocusMode.h"
#import "GBCameraFocusRange.h"
#import "GBCameraQuality.h"
#import "GBDuration.h"
#import <Foundation/Foundation.h>
@protocol GBCameraCaptureHandler;
@protocol GBVideoFrameGen;


@protocol GBCameraControllerGen

- (void)initialize:(BOOL)audio;

- (void)setAudioEnable:(BOOL)enable;

- (void)startCamera;

- (void)stopCamera;

- (void)switchFront:(BOOL)front;

- (BOOL)isFront;

- (void)setFlashMode:(GBCameraFlash)mode;

- (GBCameraFlash)getFlashMode;

- (void)setQuality:(GBCameraQuality)quality;

- (GBCameraQuality)getQuality;

- (void)setSloMo:(BOOL)flag;

- (BOOL)getSloMo;

- (int32_t)getMaxFrameRate;

- (int32_t)getDefaultFrameRate;

- (void)setFrameDuration:(int64_t)value
                   scale:(int32_t)scale;

- (nonnull GBDuration *)getFrameDuration;

- (void)setExposureMode:(GBCameraExposureMode)mode;

- (GBCameraExposureMode)getExposureMode;

- (void)setExposurePoint:(float)x
                       y:(float)y;

- (void)setExposureEv:(float)ev;

- (float)getExposureEv;

- (float)getExposureMaxEv;

- (float)getExposureMinEv;

- (void)setExposureDuration:(float)seconds;

- (float)getExposureDuration;

- (float)getExposureMinDuration;

- (float)getExposureMaxDuration;

- (void)setISO:(int32_t)iso;

- (int32_t)getISO;

- (int32_t)getISOMax;

- (int32_t)getISOMin;

- (void)setFocusMode:(GBCameraFocusMode)mode;

- (GBCameraFocusMode)getFocusMode;

/** lens form 0.0 to 1.0, shortest to furthest */
- (void)setFocusLens:(float)lens;

- (float)getFocusLens;

- (float)getFocusMax;

- (float)getFocusMin;

- (void)setFocusPoint:(float)x
                    y:(float)y;

- (void)setFocusAutoRange:(GBCameraFocusRange)range;

- (GBCameraFocusRange)getFocusAutoRange;

- (void)setZoom:(float)zoom;

- (float)getZoom;

- (float)getZoomMax;

/** minimum value is 1.0 */
- (float)getZoomMin;

- (nullable id<GBVideoFrameGen>)captureOneFrame;

- (void)asnyOneFrame;

- (void)asnyOnePicture;

- (void)setCaptureHandler:(nullable id<GBCameraCaptureHandler>)handler;

- (void)setCaptureMode:(GBCameraCaptureMode)mode;

- (GBCameraCaptureMode)getCaptureMode;

- (void)setImmediaPause:(BOOL)flag;

- (nonnull NSString *)getDebugInfo;

@end
