// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#import <Foundation/Foundation.h>

/**@import "ui.djinni" */
typedef NS_ENUM(NSInteger, GBCameraFlash)
{
    GBCameraFlashOn,
    GBCameraFlashOff,
    GBCameraFlashAuto,
};
