// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, GBCameraQuality)
{
    GBCameraQualityP288,
    GBCameraQualityP480,
    GBCameraQualityP720,
    GBCameraQualityP1080,
    GBCameraQualityP1920,
};
