// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from config.djinni

#import <Foundation/Foundation.h>
@class GBConfigGen;


@interface GBConfigGen : NSObject

+ (nullable GBConfigGen *)create;

- (BOOL)initialize:(nonnull NSString *)param;

- (nonnull NSString *)getString:(nonnull NSString *)type;

- (int32_t)getInt:(nonnull NSString *)type;

- (float)getFloat:(nonnull NSString *)type;

- (int64_t)getI64:(nonnull NSString *)type;

- (void)setString:(nonnull NSString *)type
            value:(nonnull NSString *)value;

- (void)setInt:(nonnull NSString *)type
         value:(int32_t)value;

- (void)setFloat:(nonnull NSString *)type
           value:(float)value;

- (void)setI64:(nonnull NSString *)type
         value:(int64_t)value;

- (int32_t)getArrayCount;

- (nullable GBConfigGen *)getArrayItem:(int32_t)index;

- (nullable GBConfigGen *)getSubConfig:(nonnull NSString *)key;

@end
