// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#include "crash_handler_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol GBCrashHandlerGen;

namespace djinni_generated {

class CrashHandlerGen
{
public:
    using CppType = std::shared_ptr<::gearsbox::CrashHandlerGen>;
    using CppOptType = std::shared_ptr<::gearsbox::CrashHandlerGen>;
    using ObjcType = id<GBCrashHandlerGen>;

    using Boxed = CrashHandlerGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

