// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import "GBDeviceOrientation.h"
#import <Foundation/Foundation.h>


@protocol GBDeviceGen

- (GBDeviceOrientation)getOrientation;

@end
