// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#import "GBDuration.h"


@implementation GBDuration

- (nonnull instancetype)initWithValue:(int64_t)value
                                scale:(int32_t)scale
{
    if (self = [super init]) {
        _value = value;
        _scale = scale;
    }
    return self;
}

+ (nonnull instancetype)durationWithValue:(int64_t)value
                                    scale:(int32_t)scale
{
    return [[self alloc] initWithValue:value
                                 scale:scale];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p value:%@ scale:%@>", self.class, (void *)self, @(self.value), @(self.scale)];
}

@end
