// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#import "GBDuration+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Duration::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I64::toCpp(obj.value),
            ::djinni::I32::toCpp(obj.scale)};
}

auto Duration::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[GBDuration alloc] initWithValue:(::djinni::I64::fromCpp(cpp.value))
                                       scale:(::djinni::I32::fromCpp(cpp.scale))];
}

}  // namespace djinni_generated
