// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#import <Foundation/Foundation.h>

@interface GBDuration : NSObject
- (nonnull instancetype)initWithValue:(int64_t)value
                                scale:(int32_t)scale;
+ (nonnull instancetype)durationWithValue:(int64_t)value
                                    scale:(int32_t)scale;

@property (nonatomic, readonly) int64_t value;

@property (nonatomic, readonly) int32_t scale;

@end
