// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#import "GBDuration.h"
#include "duration.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class GBDuration;

namespace djinni_generated {

struct Duration
{
    using CppType = ::gearsbox::Duration;
    using ObjcType = GBDuration*;

    using Boxed = Duration;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
