// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#include "file_info_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol GBFileInfoGen;

namespace djinni_generated {

class FileInfoGen
{
public:
    using CppType = std::shared_ptr<::gearsbox::FileInfoGen>;
    using CppOptType = std::shared_ptr<::gearsbox::FileInfoGen>;
    using ObjcType = id<GBFileInfoGen>;

    using Boxed = FileInfoGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

