// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import <Foundation/Foundation.h>


@protocol GBFileInfoGen

- (BOOL)initialize:(nonnull NSString *)path;

- (int64_t)getSize;

- (nonnull NSDate *)getCreateDate;

- (nonnull NSString *)getName;

- (nonnull NSString *)getSuffix;

- (nonnull NSString *)getPrefix;

- (nonnull NSString *)getPath;

@end
