// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import <Foundation/Foundation.h>
@protocol GBCameraControllerGen;
@protocol GBPlatformUtilityGen;


@interface GBInstanceGetterGen : NSObject

+ (nullable id<GBCameraControllerGen>)getCameraController;

+ (void)setCameraController:(nullable id<GBCameraControllerGen>)camera;

+ (nullable id<GBPlatformUtilityGen>)getPlatformUtility;

+ (void)setPlatformUtility:(nullable id<GBPlatformUtilityGen>)mgr;

@end
