// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import <Foundation/Foundation.h>


@protocol GBPlatformUtilityGen

- (void)endEniting:(BOOL)force;

- (nonnull NSString *)getRootDirectory;

- (nonnull NSString *)getPackFilePath:(nonnull NSString *)file;

@end
