// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import "GBPlatformUtilityGen+Private.h"
#import "GBPlatformUtilityGen.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "GBPlatformExecutorGen+Private.h"
#import "GBPlatformUtilityGen+Private.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface GBPlatformUtilityGen ()

- (id)initWithCpp:(const std::shared_ptr<::gearsbox::PlatformUtilityGen>&)cppRef;

@end

@implementation GBPlatformUtilityGen {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::gearsbox::PlatformUtilityGen>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::gearsbox::PlatformUtilityGen>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable GBPlatformUtilityGen *)instance {
    try {
        auto r = ::gearsbox::PlatformUtilityGen::instance();
        return ::djinni_generated::PlatformUtilityGen::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)setPlatofrmExcutor:(nullable id<GBPlatformExecutorGen>)excuser {
    try {
        _cppRefHandle.get()->setPlatofrmExcutor(::djinni_generated::PlatformExecutorGen::toCpp(excuser));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable id<GBPlatformExecutorGen>)getExcutor {
    try {
        auto r = _cppRefHandle.get()->getExcutor();
        return ::djinni_generated::PlatformExecutorGen::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto PlatformUtilityGen::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto PlatformUtilityGen::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<GBPlatformUtilityGen>(cpp);
}

}  // namespace djinni_generated

@end
