// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import "GBPlatformExecutorGen+Private.h"
#import "GBPlatformExecutorGen.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class PlatformExecutorGen::ObjcProxy final
: public ::gearsbox::PlatformExecutorGen
, public ::djinni::ObjcProxyCache::Handle<ObjcType>
{
public:
    using Handle::Handle;
    void endEniting(bool c_force) override
    {
        @autoreleasepool {
            [Handle::get() endEniting:(::djinni::Bool::fromCpp(c_force))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto PlatformExecutorGen::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto PlatformExecutorGen::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).Handle::get();
}

}  // namespace djinni_generated
