// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import <Foundation/Foundation.h>
@class GBPlatformUtilityGen;
@protocol GBPlatformExecutorGen;


@interface GBPlatformUtilityGen : NSObject

+ (nullable GBPlatformUtilityGen *)instance;

- (void)setPlatofrmExcutor:(nullable id<GBPlatformExecutorGen>)excuser;

- (nullable id<GBPlatformExecutorGen>)getExcutor;

@end
