// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import <Foundation/Foundation.h>


@protocol GBPlatformUtilityGen

- (void)endEniting:(BOOL)force;

/**ios home directory */
- (nonnull NSString *)getHomeDirectory;

- (nonnull NSString *)getPackFilePath:(nonnull NSString *)file;

- (nonnull NSString *)getPackFileBuffer:(nonnull NSString *)file;

/**copy pack file to home directory and return path in home directory */
- (nonnull NSString *)getPackFileToHomePath:(nonnull NSString *)file;

@end
