// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import "GBTaskInfo.h"
#include "task_info.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class GBTaskInfo;

namespace djinni_generated {

struct TaskInfo
{
    using CppType = ::gearsbox::TaskInfo;
    using ObjcType = GBTaskInfo*;

    using Boxed = TaskInfo;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
