// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import <Foundation/Foundation.h>
@class GBTaskManagerGen;
@protocol GBTaskGen;


@interface GBTaskManagerGen : NSObject

+ (nullable GBTaskManagerGen *)instance;

- (void)addTask:(nullable id<GBTaskGen>)task;

- (void)addDelayTask:(int64_t)delay
            repeated:(int64_t)repeated;

@end
