// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import "GBTaskInfo+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto TaskInfo::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I64::toCpp(obj.delay),
            ::djinni::Bool::toCpp(obj.repeate)};
}

auto TaskInfo::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[GBTaskInfo alloc] initWithDelay:(::djinni::I64::fromCpp(cpp.delay))
                                     repeate:(::djinni::Bool::fromCpp(cpp.repeate))];
}

}  // namespace djinni_generated
