// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import "GBTaskManagerGen+Private.h"
#import "GBTaskManagerGen.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "GBTaskGen+Private.h"
#import "GBTaskManagerGen+Private.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface GBTaskManagerGen ()

- (id)initWithCpp:(const std::shared_ptr<::gearsbox::TaskManagerGen>&)cppRef;

@end

@implementation GBTaskManagerGen {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::gearsbox::TaskManagerGen>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::gearsbox::TaskManagerGen>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable GBTaskManagerGen *)instance {
    try {
        auto r = ::gearsbox::TaskManagerGen::instance();
        return ::djinni_generated::TaskManagerGen::fromCpp(r);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)addTask:(nullable id<GBTaskGen>)task {
    try {
        _cppRefHandle.get()->addTask(::djinni_generated::TaskGen::toCpp(task));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)addDelayTask:(int64_t)delay
            repeated:(int64_t)repeated {
    try {
        _cppRefHandle.get()->addDelayTask(::djinni::I64::toCpp(delay),
                                          ::djinni::I64::toCpp(repeated));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto TaskManagerGen::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto TaskManagerGen::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<GBTaskManagerGen>(cpp);
}

}  // namespace djinni_generated

@end
