// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import "GBTaskInfo.h"
#import <Foundation/Foundation.h>


@protocol GBTaskGen

- (void)excuse:(nonnull GBTaskInfo *)info;

@end
