// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import <Foundation/Foundation.h>

@interface GBTaskInfo : NSObject
- (nonnull instancetype)initWithDelay:(int64_t)delay
                              repeate:(BOOL)repeate;
+ (nonnull instancetype)taskInfoWithDelay:(int64_t)delay
                                  repeate:(BOOL)repeate;

@property (nonatomic, readonly) int64_t delay;

@property (nonatomic, readonly) BOOL repeate;

@end
