// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import "GBTaskInfo+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto TaskInfo::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.tarskId),
            ::djinni::I64::toCpp(obj.delay),
            ::djinni::I32::toCpp(obj.repeated),
            ::djinni::I64::toCpp(obj.elapsed)};
}

auto TaskInfo::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[GBTaskInfo alloc] initWithTarskId:(::djinni::I32::fromCpp(cpp.tarsk_id))
                                         delay:(::djinni::I64::fromCpp(cpp.delay))
                                      repeated:(::djinni::I32::fromCpp(cpp.repeated))
                                       elapsed:(::djinni::I64::fromCpp(cpp.elapsed))];
}

}  // namespace djinni_generated
