// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import "GBTaskInfo.h"


@implementation GBTaskInfo

- (nonnull instancetype)initWithDelay:(int64_t)delay
                              repeate:(BOOL)repeate
{
    if (self = [super init]) {
        _delay = delay;
        _repeate = repeate;
    }
    return self;
}

+ (nonnull instancetype)taskInfoWithDelay:(int64_t)delay
                                  repeate:(BOOL)repeate
{
    return [[self alloc] initWithDelay:delay
                               repeate:repeate];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p delay:%@ repeate:%@>", self.class, (void *)self, @(self.delay), @(self.repeate)];
}

@end
