// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import <Foundation/Foundation.h>
@protocol GBTaskInfoGen;


@protocol GBTaskExcuserGen

- (void)excuse:(nullable id<GBTaskInfoGen>)info;

@end
