// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import "GBTaskGen+Private.h"
#import "GBTaskGen.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIObjcWrapperCache+Private.h"
#import "GBTaskInfo+Private.h"
#include <exception>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface GBTaskGenCppProxy : NSObject<GBTaskGen>

- (id)initWithCpp:(const std::shared_ptr<::gearsbox::TaskGen>&)cppRef;

@end

@implementation GBTaskGenCppProxy {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::gearsbox::TaskGen>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::gearsbox::TaskGen>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)excuse:(nonnull GBTaskInfo *)info {
    try {
        _cppRefHandle.get()->excuse(::djinni_generated::TaskInfo::toCpp(info));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

class TaskGen::ObjcProxy final
: public ::gearsbox::TaskGen
, public ::djinni::ObjcProxyCache::Handle<ObjcType>
{
public:
    using Handle::Handle;
    void excuse(const ::gearsbox::TaskInfo & c_info) override
    {
        @autoreleasepool {
            [Handle::get() excuse:(::djinni_generated::TaskInfo::fromCpp(c_info))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto TaskGen::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    if ([(id)objc isKindOfClass:[GBTaskGenCppProxy class]]) {
        return ((GBTaskGenCppProxy*)objc)->_cppRefHandle.get();
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto TaskGen::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    if (auto cppPtr = dynamic_cast<ObjcProxy*>(cpp.get())) {
        return cppPtr->Handle::get();
    }
    return ::djinni::get_cpp_proxy<GBTaskGenCppProxy>(cpp);
}

}  // namespace djinni_generated

@end
