// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#include "task_excuser_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol GBTaskExcuserGen;

namespace djinni_generated {

class TaskExcuserGen
{
public:
    using CppType = std::shared_ptr<::gearsbox::TaskExcuserGen>;
    using CppOptType = std::shared_ptr<::gearsbox::TaskExcuserGen>;
    using ObjcType = id<GBTaskExcuserGen>;

    using Boxed = TaskExcuserGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

