// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import <Foundation/Foundation.h>
@class GBTaskManagerGen;
@protocol GBTaskExcuserGen;
@protocol GBTaskInfoGen;


/**
 *delay<0 immediately
 *delay==0 next frame
 */
@interface GBTaskManagerGen : NSObject

+ (nullable GBTaskManagerGen *)instance;

+ (nullable id<GBTaskInfoGen>)createInfo:(int64_t)taskId
                                   delay:(int64_t)delay
                                repeated:(int32_t)repeated;

- (void)addTask:(int64_t)taskId
          delay:(int64_t)delay
       repeated:(int64_t)repeated
           task:(nullable id<GBTaskExcuserGen>)task;

- (void)addTaskI:(int64_t)taskId
            task:(nullable id<GBTaskExcuserGen>)task;

- (void)addTaskInfo:(nullable id<GBTaskInfoGen>)task
        taskExcuser:(nullable id<GBTaskExcuserGen>)taskExcuser;

- (void)addTaskExcuser:(nullable id<GBTaskExcuserGen>)task;

- (void)removeTask:(int64_t)taskId;

@end
