// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import <Foundation/Foundation.h>
@class GBTimerGen;
@protocol GBTaskExcuserGen;


@interface GBTimerGen : NSObject

+ (nullable GBTimerGen *)create:(int64_t)timeout
                    repeatTimes:(int32_t)repeatTimes
                         hander:(nullable id<GBTaskExcuserGen>)hander;

- (BOOL)start;

- (void)stop;

- (int32_t)getRepeated;

- (int64_t)getTimePassed;

- (BOOL)isRunning;

@end
