// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#import <Foundation/Foundation.h>


@protocol GBTimerHandlerGen

- (void)handler:(int64_t)timePassed
       repeated:(int32_t)repeated;

@end
