// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#include "typer_convertor.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol GBTyperConvertor;

namespace djinni_generated {

class TyperConvertor
{
public:
    using CppType = std::shared_ptr<::gearsbox::TyperConvertor>;
    using CppOptType = std::shared_ptr<::gearsbox::TyperConvertor>;
    using ObjcType = id<GBTyperConvertor>;

    using Boxed = TyperConvertor;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

