// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import "GBTyperConvertor+Private.h"
#import "GBTyperConvertor.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "GBArgbColor+Private.h"
#import "GBViewFrame+Private.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class TyperConvertor::ObjcProxy final
: public ::gearsbox::TyperConvertor
, public ::djinni::ObjcProxyCache::Handle<ObjcType>
{
public:
    using Handle::Handle;
    void convertUIColor(const ::gearsbox::ArgbColor & c_color) override
    {
        @autoreleasepool {
            [Handle::get() convertUIColor:(::djinni_generated::ArgbColor::fromCpp(c_color))];
        }
    }
    void convertUIRect(const ::gearsbox::ViewFrame & c_rect) override
    {
        @autoreleasepool {
            [Handle::get() convertUIRect:(::djinni_generated::ViewFrame::fromCpp(c_rect))];
        }
    }
    void convertUIConstraintType(::gearsbox::ConstraintType c_type) override
    {
        @autoreleasepool {
            [Handle::get() convertUIConstraintType:(::djinni::Enum<::gearsbox::ConstraintType, GBConstraintType>::fromCpp(c_type))];
        }
    }
    void convertUITextBoarder(::gearsbox::TextBoarder c_type) override
    {
        @autoreleasepool {
            [Handle::get() convertUITextBoarder:(::djinni::Enum<::gearsbox::TextBoarder, GBTextBoarder>::fromCpp(c_type))];
        }
    }
    void convertUITextAlign(::gearsbox::TextAlign c_type) override
    {
        @autoreleasepool {
            [Handle::get() convertUITextAlign:(::djinni::Enum<::gearsbox::TextAlign, GBTextAlign>::fromCpp(c_type))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto TyperConvertor::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto TyperConvertor::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).Handle::get();
}

}  // namespace djinni_generated
