// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#import <Foundation/Foundation.h>
@class GBVideoInfoGen;
@protocol GBVideoFrameGen;


@interface GBVideoInfoGen : NSObject

/** create at fist time, return after second time */
+ (nullable GBVideoInfoGen *)getVideoInfo:(nonnull NSString *)path
                                 outWidth:(int32_t)outWidth
                                outHeight:(int32_t)outHeight;

- (nonnull NSString *)getName;

- (nonnull NSString *)getPath;

- (int32_t)getFPS;

- (int32_t)getWidth;

- (int32_t)getHeight;

- (int64_t)getFrameAmount;

/**by second */
- (int64_t)getDuration;

- (nullable id<GBVideoFrameGen>)getVideoFrame;

@end
