// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#import <Foundation/Foundation.h>


@protocol GBVideoWriterResultHandler

- (void)onComplete:(BOOL)success
              path:(nonnull NSString *)path;

/** in slo-mo mode memory full */
- (void)beforeForceStop;

@end
