// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, GBViewEvent)
{
    GBViewEventNone,
    GBViewEventTap,
    GBViewEventTextChange,
};
