// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#include "video_encoder_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol GBVideoEncoderGen;

namespace djinni_generated {

class VideoEncoderGen
{
public:
    using CppType = std::shared_ptr<::gearsbox::VideoEncoderGen>;
    using CppOptType = std::shared_ptr<::gearsbox::VideoEncoderGen>;
    using ObjcType = id<GBVideoEncoderGen>;

    using Boxed = VideoEncoderGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

