// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, GBVideoOrientation)
{
    GBVideoOrientationLandspace0,
    GBVideoOrientationLandspace180,
    GBVideoOrientationPortrait90,
    GBVideoOrientationPortrait270,
};
