// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#include "video_writer_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class GBVideoWriterGen;

namespace djinni_generated {

class VideoWriterGen
{
public:
    using CppType = std::shared_ptr<::gearsbox::VideoWriterGen>;
    using CppOptType = std::shared_ptr<::gearsbox::VideoWriterGen>;
    using ObjcType = GBVideoWriterGen*;

    using Boxed = VideoWriterGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

