// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import "GBViewConf.h"
#include "view_conf.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class GBViewConf;

namespace djinni_generated {

struct ViewConf
{
    using CppType = ::gearsbox::ViewConf;
    using ObjcType = GBViewConf*;

    using Boxed = ViewConf;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
