// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#import <Foundation/Foundation.h>
@protocol GBVideoFrameGen;


@protocol GBVideoEncoderGen

- (BOOL)initialize:(nonnull NSString *)filepath
               fps:(int32_t)fps
           bitrate:(int32_t)bitrate
             width:(int32_t)width
            height:(int32_t)height
             frame:(nullable id<GBVideoFrameGen>)frame;

- (void)encodeFrame:(nullable id<GBVideoFrameGen>)frame;

- (void)saveNRelease;

@end
