// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#import <Foundation/Foundation.h>
@class GBVideoWriterGen;
@protocol GBVideoFrameGen;


@interface GBVideoWriterGen : NSObject

+ (nullable GBVideoWriterGen *)create;

- (void)setFilePath:(nonnull NSString *)file;

- (void)setFPS:(int32_t)fps;

- (void)setBitRate:(int32_t)rate;

- (void)encodeFrame:(nullable id<GBVideoFrameGen>)frame;

- (void)start:(int64_t)interval;

- (void)pause;

- (void)resume;

- (BOOL)isRunning;

- (void)saveNRlease;

@end
