// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#import "GBVideoOrientation.h"
#import <Foundation/Foundation.h>
@class GBVideoWriterGen;
@protocol GBVideoEncoderGen;
@protocol GBVideoFrameGen;
@protocol GBVideoWriterResultHandler;


@interface GBVideoWriterGen : NSObject

+ (nullable GBVideoWriterGen *)create;

- (void)setReslutHandler:(nullable id<GBVideoWriterResultHandler>)handler;

- (void)setFilePath:(nonnull NSString *)file;

- (nonnull NSString *)getFilePath;

- (void)setFPS:(int32_t)fps;

- (int32_t)getFPS;

- (void)setBitRate:(int32_t)rate;

- (void)setOrientation:(GBVideoOrientation)ori;

- (void)setVideoEncoder:(nullable id<GBVideoEncoderGen>)encoder;

- (void)encodeFrame:(nullable id<GBVideoFrameGen>)frame;

- (void)start:(int64_t)interval;

- (void)pause;

- (void)resume;

- (BOOL)isRunning;

- (void)setInterval:(int64_t)interval;

- (void)saveNRlease;

@end
