// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#include "video_info_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class GBVideoInfoGen;

namespace djinni_generated {

class VideoInfoGen
{
public:
    using CppType = std::shared_ptr<::gearsbox::VideoInfoGen>;
    using CppOptType = std::shared_ptr<::gearsbox::VideoInfoGen>;
    using ObjcType = GBVideoInfoGen*;

    using Boxed = VideoInfoGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

