// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#import <Foundation/Foundation.h>
@protocol GBViewGen;


@protocol GBViewFactoryGen

- (nullable id<GBViewGen>)createView:(nonnull NSString *)id;

@end
