// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#include "test_mgr_gen.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class GBTestMgrGen;

namespace djinni_generated {

class TestMgrGen
{
public:
    using CppType = std::shared_ptr<::gearsbox::TestMgrGen>;
    using CppOptType = std::shared_ptr<::gearsbox::TestMgrGen>;
    using ObjcType = GBTestMgrGen*;

    using Boxed = TestMgrGen;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

