// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

#include <memory>

namespace gearsbox {

class CrashHandlerGen;

class BreakpadGen {
public:
    virtual ~BreakpadGen() {}

    virtual void start() = 0;

    virtual void stop() = 0;

    virtual void setUploadUrl() = 0;

    virtual void setHandler(const std::shared_ptr<CrashHandlerGen> & hander) = 0;
};

}  // namespace gearsbox
