// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#pragma once

#include <functional>

namespace gearsbox {

enum class CameraFlash : int {
    ON,
    OFF,
    AUTO,
};

}  // namespace gearsbox

namespace std {

template <>
struct hash<::gearsbox::CameraFlash> {
    size_t operator()(::gearsbox::CameraFlash type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
