// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#include "camera_config_gen.hpp"  // my header
#include "camera_flash.hpp"
#include "camera_quality.hpp"

namespace gearsbox {

std::string const CameraConfigGen::FLASH_MODE = {"flash_mode"};

std::string const CameraConfigGen::FLASH_MODE_AUTO = {"auto"};

std::string const CameraConfigGen::FLASH_MODE_ON = {"on"};

std::string const CameraConfigGen::FLASH_MODE_OFF = {"off"};

std::string const CameraConfigGen::QUALITY = {"quality"};

std::string const CameraConfigGen::QUALITY_360P = {"360p"};

std::string const CameraConfigGen::QUALITY_480P = {"480p"};

std::string const CameraConfigGen::QUALITY_720P = {"720p"};

std::string const CameraConfigGen::QUALITY_1080P = {"1080p"};

}  // namespace gearsbox
