// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#pragma once

#include <memory>
#include <string>

namespace gearsbox {

class ConfigGen;
enum class CameraFlash;
enum class CameraQuality;

class CameraConfigGen {
public:
    virtual ~CameraConfigGen() {}

    static std::string const FLASH_MODE;

    static std::string const FLASH_MODE_AUTO;

    static std::string const FLASH_MODE_ON;

    static std::string const FLASH_MODE_OFF;

    static std::string const QUALITY;

    static std::string const QUALITY_360P;

    static std::string const QUALITY_480P;

    static std::string const QUALITY_720P;

    static std::string const QUALITY_1080P;

    static std::shared_ptr<CameraConfigGen> instance();

    virtual bool initialize(const std::shared_ptr<ConfigGen> & cfg) = 0;

    virtual CameraFlash getFlashMode() = 0;

    virtual CameraQuality getQuatityLevel() = 0;

    virtual void setFlashMode(CameraFlash mode) = 0;

    virtual void setQuatityLevel(CameraQuality quality) = 0;
};

}  // namespace gearsbox
