// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#pragma once

#include <functional>

namespace gearsbox {

enum class CameraFocusRange : int {
    NONE,
    NEAR,
    FAR,
};

}  // namespace gearsbox

namespace std {

template <>
struct hash<::gearsbox::CameraFocusRange> {
    size_t operator()(::gearsbox::CameraFocusRange type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
