// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#pragma once

#include <functional>

namespace gearsbox {

enum class CameraExposureMode : int {
    NONE,
    /** ios Indicates that the exposure should be locked at its current value. */
    LOCKED,
    /** ios Indicates that the device should automatically adjust exposure once and then change the exposure mode to Locked. */
    AUTOEXPOSE,
    /** ios Indicates that the device should automatically adjust exposure when needed. */
    CONTINUOUSAUTOEXPOSURE,
    /**ios Indicates that the device should only adjust exposure according to user provided ISO, exposureDuration values. */
    MODECUSTOM,
};

}  // namespace gearsbox

namespace std {

template <>
struct hash<::gearsbox::CameraExposureMode> {
    size_t operator()(::gearsbox::CameraExposureMode type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
