// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#pragma once

#include <functional>

namespace gearsbox {

enum class CameraFocusMode : int {
    NONE,
    LOCKED,
    AUTOFOCUS,
    CONTINUOUSAUTOFOCUS,
};

}  // namespace gearsbox

namespace std {

template <>
struct hash<::gearsbox::CameraFocusMode> {
    size_t operator()(::gearsbox::CameraFocusMode type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
