// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#pragma once

#include <functional>

namespace gearsbox {

enum class CameraCaptureMode : int {
    NONE,
    IMMEDIATE_VIDEO,
    VIDEO,
    PHOTO,
};

}  // namespace gearsbox

namespace std {

template <>
struct hash<::gearsbox::CameraCaptureMode> {
    size_t operator()(::gearsbox::CameraCaptureMode type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
