// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#pragma once

#include <memory>
#include <string>

namespace gearsbox {

class VideoFrameGen;

class CameraCaptureHandler {
public:
    virtual ~CameraCaptureHandler() {}

    virtual void captureOutput(const std::shared_ptr<VideoFrameGen> & picture, const std::string & error) = 0;
};

}  // namespace gearsbox
