// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

namespace gearsbox {

enum class DeviceOrientation;

class DeviceGen {
public:
    virtual ~DeviceGen() {}

    virtual DeviceOrientation getOrientation() = 0;
};

}  // namespace gearsbox
