// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

#include <memory>
#include <string>

namespace gearsbox {

class CameraControllerGen;
class ConfigGen;
class DeviceGen;
class PlatformUtilityGen;

class InstanceGetterGen {
public:
    virtual ~InstanceGetterGen() {}

    static std::shared_ptr<CameraControllerGen> getCameraController();

    static void setCameraController(const std::shared_ptr<CameraControllerGen> & camera);

    static std::shared_ptr<PlatformUtilityGen> getPlatformUtility();

    static void setPlatformUtility(const std::shared_ptr<PlatformUtilityGen> & mgr);

    static std::shared_ptr<DeviceGen> getDevice();

    static void setDevice(const std::shared_ptr<DeviceGen> & device);

    static std::shared_ptr<ConfigGen> getConfig(const std::string & id);
};

}  // namespace gearsbox
