// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

#include <memory>
#include <string>

namespace gearsbox {

enum class LangType;

class LanguageStoreGen {
public:
    virtual ~LanguageStoreGen() {}

    static std::shared_ptr<LanguageStoreGen> instance();

    virtual bool initialize(const std::string & param) = 0;

    virtual void setLanguage(LangType lang) = 0;

    virtual LangType getLanguage() = 0;

    virtual std::string getString(const std::string & type) = 0;
};

}  // namespace gearsbox
