// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

namespace gearsbox {

class PlatformExecutorGen {
public:
    virtual ~PlatformExecutorGen() {}

    virtual void endEniting(bool force) = 0;
};

}  // namespace gearsbox
