// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

#include <string>

namespace gearsbox {

class PlatformUtilityGen {
public:
    virtual ~PlatformUtilityGen() {}

    virtual void endEniting(bool force) = 0;

    virtual std::string getRootDirectory() = 0;

    virtual std::string getPackFilePath(const std::string & file) = 0;
};

}  // namespace gearsbox
