// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

#include <cstdint>
#include <string>

namespace gearsbox {

class TaskInfoGen {
public:
    virtual ~TaskInfoGen() {}

    virtual int64_t getTaskId() = 0;

    virtual int64_t getDelay() = 0;

    virtual int32_t getRepeated() = 0;

    virtual int64_t getAssignTick() = 0;

    virtual std::string getData() = 0;

    virtual std::string getValue(const std::string & key) = 0;

    virtual int64_t getIValue(const std::string & key) = 0;

    virtual double getFValue(const std::string & key) = 0;

    virtual void setTaskId(int64_t id) = 0;

    virtual void setDelay(int64_t delay) = 0;

    virtual void setRepeated(int32_t repeated) = 0;

    virtual void setAssignTick(int64_t assign) = 0;

    virtual void setData(const std::string & data) = 0;

    virtual void setValue(const std::string & key, const std::string & value) = 0;

    virtual void setIValue(const std::string & key, int64_t value) = 0;

    virtual void setFValue(const std::string & key, double value) = 0;
};

}  // namespace gearsbox
