// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

#include <cstdint>
#include <memory>

namespace gearsbox {

class TaskGen;

class TaskManagerGen {
public:
    virtual ~TaskManagerGen() {}

    static std::shared_ptr<TaskManagerGen> instance();

    virtual void addTask(const std::shared_ptr<TaskGen> & task) = 0;

    virtual void addDelayTask(int64_t delay, int64_t repeated) = 0;
};

}  // namespace gearsbox
