// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

namespace gearsbox {

struct TaskInfo;

class TaskGen {
public:
    virtual ~TaskGen() {}

    virtual void excuse(const TaskInfo & info) = 0;
};

}  // namespace gearsbox
