// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace gearsbox {

struct TaskInfo final {
    int64_t tarsk_id;
    int64_t delay;
    int32_t repeated;
    int64_t elapsed;

    TaskInfo(int64_t tarsk_id_,
             int64_t delay_,
             int32_t repeated_,
             int64_t elapsed_)
    : tarsk_id(std::move(tarsk_id_))
    , delay(std::move(delay_))
    , repeated(std::move(repeated_))
    , elapsed(std::move(elapsed_))
    {}
};

}  // namespace gearsbox
