// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from gearsbox.djinni

#pragma once

#include <memory>

namespace gearsbox {

class TaskInfoGen;

class TaskExcuserGen {
public:
    virtual ~TaskExcuserGen() {}

    virtual void excuse(const std::shared_ptr<TaskInfoGen> & info) = 0;
};

}  // namespace gearsbox
