// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

namespace gearsbox {

enum class ConstraintType;
enum class TextAlign;
enum class TextBoarder;
enum class TextKeyboard;
struct ArgbColor;
struct ViewFrame;

class TyperConvertorDummy {
public:
    virtual ~TyperConvertorDummy() {}

    virtual void convertUIColor(const ArgbColor & color) = 0;

    virtual void convertUIRect(const ViewFrame & rect) = 0;

    virtual void convertUIConstraintType(ConstraintType type) = 0;

    virtual void convertUITextBoarder(TextBoarder type) = 0;

    virtual void convertUITextAlign(TextAlign type) = 0;

    virtual void convertKeyboardType(TextKeyboard type) = 0;
};

}  // namespace gearsbox
