// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include <memory>
#include <string>

namespace gearsbox {

class ViewFactoryGen;
class ViewGen;

class UiManagerGen {
public:
    virtual ~UiManagerGen() {}

    static std::shared_ptr<UiManagerGen> instance();

    virtual bool initialize(const std::string & param, const std::shared_ptr<ViewFactoryGen> & factory) = 0;

    virtual void inject(const std::shared_ptr<ViewGen> & view) = 0;

    virtual std::shared_ptr<ViewGen> getView(const std::string & id) = 0;

    virtual std::shared_ptr<ViewGen> addView(const std::shared_ptr<ViewGen> & view) = 0;

    virtual void removeView(const std::string & id) = 0;
};

}  // namespace gearsbox
