// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include <memory>

namespace gearsbox {

enum class TextAlign;
enum class TextBoarder;
struct ArgbColor;
struct ViewFrame;

class UiValueCheckerGen {
public:
    virtual ~UiValueCheckerGen() {}

    static std::shared_ptr<UiValueCheckerGen> instance();

    virtual bool isValidColor(const ArgbColor & value) = 0;

    virtual bool isValidFrame(const ViewFrame & value) = 0;

    virtual bool isValidTextBoarder(TextBoarder value) = 0;

    virtual bool isValidTextAlign(TextAlign value) = 0;
};

}  // namespace gearsbox
