// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>

namespace gearsbox {

class VideoFrameGen;
enum class VideoOrientation;

class VideoEncoderGen {
public:
    virtual ~VideoEncoderGen() {}

    virtual bool initialize(const std::string & filepath, int32_t fps, int32_t bitrate, VideoOrientation ori, int32_t width, int32_t height, const std::shared_ptr<VideoFrameGen> & frame) = 0;

    virtual void encodeFrame(const std::shared_ptr<VideoFrameGen> & frame) = 0;

    virtual void setFps(int32_t fps) = 0;

    virtual void saveNRelease() = 0;
};

}  // namespace gearsbox
