// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from camera.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>

namespace gearsbox {

class VideoFrameGen;

class VideoInfoGen {
public:
    virtual ~VideoInfoGen() {}

    /** create at fist time, return after second time */
    static std::shared_ptr<VideoInfoGen> getVideoInfo(const std::string & path, int32_t out_width, int32_t out_height);

    virtual std::string getName() = 0;

    virtual std::string getPath() = 0;

    virtual int32_t getFPS() = 0;

    virtual int32_t getWidth() = 0;

    virtual int32_t getHeight() = 0;

    virtual int64_t getFrameAmount() = 0;

    /**by second */
    virtual int64_t getDuration() = 0;

    virtual std::shared_ptr<VideoFrameGen> getVideoFrame() = 0;
};

}  // namespace gearsbox
