// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#include "view_constraint_base.hpp"  // my header
#include "view_constraint.hpp"

namespace gearsbox {

std::string const ViewConstraintBase::SELF = {"self"};

}  // namespace gearsbox
