// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include <memory>

namespace gearsbox {

class ViewGen;
struct ViewConf;

class ViewFactoryGen {
public:
    virtual ~ViewFactoryGen() {}

    virtual std::shared_ptr<ViewGen> createView(const ViewConf & conf) = 0;

    virtual bool injectView(const std::shared_ptr<ViewGen> & view) = 0;
};

}  // namespace gearsbox
