// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#pragma once

#include <functional>

namespace gearsbox {

enum class ViewEvent : int {
    NONE,
    TAP,
    TEXTCHANGE,
};

}  // namespace gearsbox

namespace std {

template <>
struct hash<::gearsbox::ViewEvent> {
    size_t operator()(::gearsbox::ViewEvent type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
