// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ui.djinni

#include "view_conf_base.hpp"  // my header
#include "view_conf.hpp"

namespace gearsbox {

ViewFrame const ViewConfBase::NOFRAME = ViewFrame(
    -1 /* x */ ,
    -1 /* y */ ,
    -1 /* w */ ,
    -1 /* h */ );

ArgbColor const ViewConfBase::NOGBCOLOR = ArgbColor(
    -1 /* a */ ,
    0 /* r */ ,
    0 /* g */ ,
    0 /* b */ );

}  // namespace gearsbox
